### ISSUE TITLE
[Fix] should be able to display different price for each channel

### ISSUE THREAD

**Issue by karola312** [saleor/saleor-dashboard#2783] opened 2022-12-02 14:42 UTC
If not able to reproduce or fixed close issues:
- https://github.com/saleor/saleor-dashboard/issues/2735

**Comment by szczecha** [comment] 2022-12-16 15:17
Closing as I'm unable to reproduce. I tried with slow 3g and in repeat 10 times - each run passed

**Closed by szczecha** 2022-12-16 15:17 UTC
Labels: automation tests
