### ISSUE TITLE
[Bug]: Bulk deleting many categories breaks the dashboard

### ISSUE THREAD

**Issue by djkato** [saleor/saleor-dashboard#4075] opened 2023-08-08 18:00 UTC
### Description of the issue

Trying to delete all categories crashes the dashboard.

### Steps to reproduce the problem

https://github.com/saleor/saleor-dashboard/assets/25299243/f4184267-0fa2-449c-bb49-7a266e5f41b9

### What did you expect to happen?

All the categories to delete without an error.

### Additional information

I have a lot of weird categories and subcategories, I can't provide the database but on request I can maybe show my database through a video call if necessary.

### Environment

Browser and version: firefox latest stable
OS and version: windows 10 
Dashboard version: dashboard v3.14.4
Core version: core v3.14.2

**Comment by djkato** [comment] 2023-08-08 18:09
It seems that if I select all, unselect the first and then delete all* it doesn't crash. Seems like when all are deleted some array becomes empty and it tries iterating over undefined or something 👍

**Comment by wojteknowacki** [comment] 2023-09-19 09:54
cant reproduce, closing

**Closed by wojteknowacki** 2023-09-19 09:54 UTC
Labels: bug, view: categories
