### ISSUE TITLE
Unable to update Company info in Dashboard

### ISSUE THREAD

**Issue by blackyzero** [saleor/saleor-dashboard#2070] opened 2022-05-28 02:23 UTC
Hello,

When trying to update company info, i get following error from Saleor console.
How could i fix it?

```
[28/May/2022 02:22:14] "OPTIONS /graphql/ HTTP/1.1" 200 0
INFO saleor.graphql.errors.handled A query had an error [PID:26314:Thread-151]
graphql.error.base.GraphQLError: Variable "$isCloudInstance" is never used in operation "ShopSettingsUpdate".
WARNING django.request Bad Request: /graphql/ [PID:26314:Thread-151]
[28/May/2022 02:22:14] "POST /graphql/ HTTP/1.1" 400 417
[28/May/2022 02:22:24] "OPTIONS /graphql/ HTTP/1.1" 200 0
```

Thank you.

**Comment by timuric** [comment] 2022-06-02 08:05
@blackyzero Could you please share mutation details and the version of the core you are running

**Comment by michalina-graczyk** [comment] 2022-06-02 10:29
@blackyzero the issue is reported here https://github.com/saleor/saleor-dashboard/issues/2039
@timuric it is already reported in clickup, so I am closing this one.

**Closed by michalina-graczyk** 2022-06-02 10:29 UTC
