### ISSUE TITLE
Unsaved changes popup when logging out

### ISSUE THREAD

**Issue by szczecha** [saleor/saleor-dashboard#2976] opened 2023-01-12 11:53 UTC
### Description of the issue
An unsaved changes popup appears when logging out

### Steps to reproduce the problem

1. Go to site settings
2. Type some changes in one of the fields (for example, Site name)
3. Log out of Saleor

### Expected Result
A popup appears before logging out (?) / Popup doesn't appear on login screen

### Actual Result
A popup appears on the login screen

### Screenshots

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/30683248/212057018-2caa3634-11b2-42d7-beff-4df1d049b3b4.png">

### HTTP request and response from inspector

```
// insert request and response here 
```

### Console output

```
// insert console output here 
```

### System information

Dashboard version:

`v3.10.0-dev` (e.g. `v3.6.0`)

Core version:

`v3.10.0-a`

Operating system:

- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [x] Chrome
- [ ] Edge
- [ ] Other

**Comment by wojteknowacki** [comment] 2023-09-21 11:10
Duplicate of the [issue](https://github.com/saleor/saleor-dashboard/issues/4149)

**Closed by wojteknowacki** 2023-09-21 11:10 UTC
Labels: bug, view: login
